### ISSUE TITLE
Work for any address of jira_server?

### ISSUE THREAD

**Issue by JinTuring** [amhammett/jira-rest-api-oauth#1]
Hi, 
it will work for any address of jira_server?
I mean the no-application-registered atlassian domain adress.
according to https://developer.atlassian.com/cloud/jira/platform/jira-rest-api-oauth-authentication/ ,
I want to access resource of other atlassian under of his authrization.
can you give any help for this?
Cheers.

**Comment by amhammett** [comment]
Hi @JinTuring,

The script is expecting the jira_server to be in the format of http://jira.url/jira.
This has been tested using Jira Server so depending on your installation things may be slightly different.

I wasn't able to find a reference of no-application-registered atlassian domain address in the docs you linked to. Are you able to provide more details?

Finally, make sure your Jira instance has been configured as outlined in the readme. You must configure application lists prior to running the script. I have added some basic exception catching to help with flow.

**Comment by JinTuring** [comment]
Hi @amhammett ,
Thanks for your reply.
I wanted a ideal way to connect to jira server under the owner's oath2 authorization something like other general social authentication/authorization process steps.

**Comment by amhammett** [comment]
Hi @JinTuring,

Jira OAuth definitely supports that process but keep in mind that it isn't completely automated end to end. Once you have completed the OAuth dance you will be able to assume the identity of the account the credentials are linked with and interact with the Jira API.

**Comment by amhammett** [comment]
I'm going to go ahead and close this issue but please feel free to suggest changes in a new issue or create a documentation Pull Request to improve the documentation regarding this.
